# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 18:40


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webhookmapping',
            unique_together=set([]),
        ),
    ]
