# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 14:31
from __future__ import unicode_literals

from django.db import migrations

from webhook_launcher.app.misc import normalize_git_url


def add_dot_git_to_repourl(apps, schema_editor):
    WebHookMapping = apps.get_model('app', 'WebHookMapping')
    for mapping in WebHookMapping.objects.all():
        mapping.repourl = normalize_git_url(mapping.repourl)
        mapping.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_flag_old_placeholders'),
    ]

    operations = [
        migrations.RunPython(add_dot_git_to_repourl,
                             reverse_code=add_dot_git_to_repourl)
    ]
